name: dit_env

dependencies:
  - contextlib2
  - cvxopt = 1.1.7
  - libgfortran = 1
  - matplotlib
  - nomkl
  - numpy >= 1.6
  - scipy >= 0.15
  - six >= 1.4
  - sphinx >= 1.3
  - pip:
    - hypothesis
    - ipython[nbconvert] == 4.0.1
    - iterutils >= 0.1.6
    - python-ternary
    - releases
    - sarge
    - sphinxcontrib-bibtex
